- name: playbook for mounting data volume
  hosts: all
  become: true
  tasks:
    - name: Creates and Formats the Partition
      shell: |
        #!/usr/bin/env bash
        storage_device=""

        # Scan devices
        sudo rescan-scsi-bus.sh -a -m -r

        # Figure out if it's using mpath or mounted disks
        if [[ -z $(ls -l /dev/mapper/mpath*) ]];then
            disk_path=/dev/sd*
            echo "Disk path is /dev/sd*"
        else
            disk_path=/dev/mapper/mpath*
            echo "Disk path is /dev/mapper/mpath*"
        fi

        # Select the First Device which is not partitioned
        for device in $(ls -1 $disk_path|egrep -v "[0-9]$")
        do
            if [[ ! -b $device"1" ]]
            then
                echo "${device}"
                storage_device=$device
            fi
        done

        # Declare native filesystem and reload with partprobe
        echo 'type=83' | sfdisk ${storage_device} || partprobe

        # Format the disk
        mkfs.xfs "${storage_device}1"

        # Mount the fs to our storage folder.
        mount -t xfs /dev/mapper/mpathb1 /<<Please replace with actual>
